<<<<<<< HEAD
 import type { Metadata,  } from "next";
import "./globals.css";
import { ParallaxObserver } from '@/components/sections/ParallaxObserver';
import { Analytics } from "@vercel/analytics/next"

export const metadata: Metadata = {
  title: "4AT AI — Finance Automation Platform",
  description:
    "Finance-native AI for reconciliation, compliance, and reporting. Purpose-built for your numbers.",
  openGraph: {
    title: "4AT AI — Finance Automation Platform",
    description: "Automate the Intelligence Layer with finance-native AI.",
    siteName: "4AT AI",
  },
=======
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
>>>>>>> eba822a4ba5f89e709ef2d53a3641fd0d3b52552
};

export default function RootLayout({
  children,
<<<<<<< HEAD
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        {children}
        <Analytics/>
        <ParallaxObserver />  {/* Replace the entire <script> block with this */}
      </body>
    </html>
  );
}
=======
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
      suppressHydrationWarning
    >
      <body className="min-h-full flex flex-col" suppressHydrationWarning>{children}</body>
    </html>
  );
}
>>>>>>> eba822a4ba5f89e709ef2d53a3641fd0d3b52552
